name: App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  common:
    name: Test Common Package
    uses: ./.github/workflows/common.yml

  frontend:
    name: Build Frontend
    uses: ./.github/workflows/frontend.yml

  build:
    name: Build & Test Manager
    runs-on: ubuntu-latest
    needs: [common, frontend]
    steps:
      - uses: actions/checkout@v4

      - name: Download frontend dist
        uses: actions/download-artifact@v4
        with:
          name: webui-dist
          path: webui/dist

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Get Go dependencies
        run: go mod download

      - name: Generate mocks
        run: ./bin/mock.sh

      - name: Generate GraphQL
        run: go tool gqlgen generate

      - name: Test
        run: go test -v -coverprofile=coverage.out ./...

      - name: Build
        run: go build -v .

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-manager
          path: coverage.out
